{"tag": "function", "depth": 1, "time": 1715005556.424205, "data": {"name": "text", "call_args": {"text": "123", "kwargs": {}, "enter": true}, "start_time": 1715005556.423708, "traceback": "Traceback (most recent call last):\n  File \"airtest/utils/logwraper.py\", line 131, in wrapper\n  File \"airtest/core/api.py\", line 572, in text\n  File \"airtest/core/helper.py\", line 19, in DEVICE\nairtest.core.error.NoDeviceError: 'No devices added.'\n", "end_time": 1715005556.424192}}
{"tag": "info", "depth": 0, "time": 1715005556.424775, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"airtest/cli/runner.py\", line 72, in runTest\n  File \"/Users/luodan/program/airtest/test1/untitled.air/untitled.py\", line 7, in <module>\n    text(\"123\")\n  File \"airtest/utils/logwraper.py\", line 131, in wrapper\n  File \"airtest/core/api.py\", line 572, in text\n  File \"airtest/core/helper.py\", line 19, in DEVICE\nairtest.core.error.NoDeviceError: 'No devices added.'\n"}}
