{"tag": "info", "depth": 0, "time": 1715006107.285397, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"airtest/cli/runner.py\", line 72, in runTest\n  File \"/Users/luodan/program/airtest/case/test1.air/test1.py\", line 9, in <module>\n    driver = WebChrome()\n  File \"/Applications/AirtestIDE.app/Contents/MacOS/airtest_selenium/proxy.py\", line 39, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"/Applications/AirtestIDE.app/Contents/MacOS/selenium/webdriver/chrome/webdriver.py\", line 75, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"/Applications/AirtestIDE.app/Contents/MacOS/selenium/webdriver/remote/webdriver.py\", line 156, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Applications/AirtestIDE.app/Contents/MacOS/selenium/webdriver/remote/webdriver.py\", line 251, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Applications/AirtestIDE.app/Contents/MacOS/selenium/webdriver/remote/webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"/Applications/AirtestIDE.app/Contents/MacOS/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 121\nCurrent browser version is 110.0.5481.177 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome\n\n"}}
